language: node_js
install: npm install 
deploy:
  provider: heroku
  api_key:
    secure: "6d14b73f-0d87-4354-a222-7dd39360d84d"
  app: node-mydiary
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage